repositories:
  - name: kyverno
    url: https://kyverno.github.io/kyverno/
releases:
  - name: kyverno
    chart: kyverno/kyverno
    namespace: kyverno
    version: 3.1.4
    values:
    - ./values.yaml
helmDefaults:
  createNamespace: true
