kyverno:
  serviceMonitor:
    enabled: true
  grafana:
    enabled: true
  installCRDs: true
  existingImagePullSecrets: []
  extraArgs:
    - --loggingFormat=text
    - --exceptionNamespace={{ include "kyverno.namespace" . }}
    - --enablePolicyException=true

policy-reporter:
  install: true
  kyvernoPlugin:
    enabled: true
